/**
 * Thin wrapper around `virtual:pwa-register/react` from vite-plugin-pwa.
 *
 * Plan 05-10: registers the service worker generated by VitePWA in
 * `autoUpdate` mode. The SW precaches the built app shell plus the
 * ngspice WASM binary (see `vite.config.ts` workbox.globPatterns) so a
 * second visit works offline.
 *
 * `autoUpdate` means a new build takes effect on the next reload without
 * prompting — we intentionally swallow `onNeedRefresh` because the UI
 * already reloads the page when we ship new versions.
 */

import { useRegisterSW as useViteRegisterSW } from 'virtual:pwa-register/react';

export function useRegisterSW() {
  return useViteRegisterSW({
    onRegisteredSW: (url) => {
      if (import.meta.env.DEV) {
        console.debug('[pwa] service worker registered:', url);
      }
    },
    onRegisterError: (err) => {
      console.error('[pwa] service worker registration error:', err);
    },
    onNeedRefresh: () => {
      // autoUpdate handles this — new SW activates on next load. We
      // intentionally do not prompt the user; the assumption is that
      // circuit state is persisted via zustand + idb-keyval so a silent
      // refresh doesn't lose work.
    },
  });
}
